# Generated by Django 3.1.5 on 2021-03-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyadmin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyadminemailverifyrecord',
            options={'verbose_name': '慧眼识垃圾邮箱验证码', 'verbose_name_plural': '慧眼识垃圾邮箱验证码'},
        ),
    ]
