# Generated by Django 3.1.7 on 2021-03-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyadmin_api', '0002_auto_20210316_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyadminemailverifyrecord',
            options={'verbose_name': '邮箱验证', 'verbose_name_plural': '邮箱验证'},
        ),
    ]
